### ISSUE TITLE
Update Dependencies & Libraries

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/iobio-components#8]
Need to update the dependencies and libraries used by bam.iobio:

- [ ] Align on a decision with IOBIO team on how these items must be updated:
    - [ ] Determine what needs to be updated
    - [ ] Determine who needs to do the updating (i.e. only OICR updates its version, or do we want IOBIO to also be in sync and update theirs)
 
**NOTE: This is where using sub-modules may be of benefit**
 
## EXPECTED OUTCOMES ##

- [ ] Dependencies in `package.json` are updated for our fork of bam.iobio (and potentially IOBIO's as well)

**Comment by demariadaniel** [comment]
Iobio team is creating a new package (iobio-charts) from the ground up. So they can use dependencies at the latest version, and won't need to update the legacy Bam.Iobio app for our purposes.

There will be updates to Stage that are related to: https://app.zenhub.com/workspaces/overture-stack-5d2e058ff67cc800011fee6b/issues/gh/overture-stack/iobio-components/11

This ticket can be closed because we will not be tracking work related to updating Bam.Iobio
